### PR TITLE
PLGOCRA2IA-1:Initial structure of new plugin-ocra2ia

### PR DESCRIPTION
**Pull request by VincentCorbel**

### CODE REVIEW

**Comment by ryahiaoui** [comment]
Please add the scm tags and jira in the plugin pom.xml

**Comment by VincentCorbel** [comment]
Ok for the scm tags, but I do not know how to feed the properties jira.
 `<properties>
        <componentName>ocra2ia</componentName>
        <jiraProjectName>PLGOCRA2IA</jiraProjectName>
        <jiraComponentId>??</jiraComponentId>
    </properties>`

**Comment by ryahiaoui** [comment]
<properties>
        <componentName>ocra2ia</componentName>
        <jiraProjectName>PLGOCRA2IA</jiraProjectName>
        <jiraComponentId>15359</jiraComponentId>
    </properties>

**Comment by ryahiaoui** [comment]
Thanks

**Pull request merged**
